from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome(executable_path='C:\Python-Driver\chromedriver.exe')

driver.get("https://login.yahoo.com/account/create")
driver.maximize_window()
print(driver.title)
driver.find_element_by_xpath('.//input[@name="firstName"]').send_keys("John")
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//input[@name="lastName"]').send_keys("Doe")
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//input[@name="yid"]').send_keys("djoe69")
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//input[@name="phone"]').send_keys("9623478900")
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//select[@name="mm"]').click()
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//option[@value="7"]').click()
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//input[@name="dd"]').send_keys('9')
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//input[@name="yyyy"]').send_keys('1994')
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//input[@name="freeformGender"]').send_keys('Male')
driver.implicitly_wait(10)
driver.find_element_by_xpath('.//button[@type="submit"]').click()
driver.implicitly_wait(10)
driver.minimize_window()
driver.close()